BoldGrid/w3-total-cache

Cache_Memcached.php

Binary protocol was enabled when available, but it cause slowdown on some environments without TCP_NODELAY set

Memcached cache engine performance degradation in last release

---

Cache_Memcached.php
ConfigCompiler.php
ConfigKeys.php
DbCache_Core.php
DbCache_WpdbInjection_QueryCaching.php
Minify_MinifiedFileRequestHandler.php
Minify_Plugin_Admin.php
ObjectCache_Plugin.php
ObjectCache_WpObjectCache_Regular.php
PgCache_ContentGrabber.php
PgCache_Plugin.php
Util_ConfigLabel.php
inc/options/parts/memcached.php

w3-total-cache fails to connect to memcached servers with binary protocol turned on.
The cause of this issue is the `\Memcached::OPT_BINARY_PROTOCOL` constant which is defined if there is support for this feature on the server running the Wordpress instance. It is however possible that the actual memcached server instance, or a proxy in between does not support it.
This change adds a config option to disable the binary protocol for memcached.
I'm not a 100% sure I updated all the relevant parts to support this new config. The core functionality is tested and works for us. This setting appears in the Admin interface and is editable there. Feedback is welcome!

add config to make memcached binary protocol optional

---

PgCache_Environment.php
Util_Rule.php

When custom .htaccess is used with no trailing line, the configuration injected by W3TC didn't insert line break before adding own rules causing a corrupt .htaccess generation

Add cr to htaccess

---

Generic_Plugin_WidgetForum.php
Generic_Plugin_WidgetNews.php
inc/widget/latest_ajax.php
inc/widget/latest_news_ajax.php

Widgets printed html-escaped <div>content</div> coming from news feed

Dont show html entities in news widget

---

Cache_File.php
Cache_File_Generic.php

Plugin didn't try to create wp-content/cache folder itself during front-end requests processing, only folders below it.
That makes deployment scripts more complex.

when wp-content/cache folder is removed - it was not created by frontend

---

PgCache_Page.php
PgCache_Plugin_Admin.php
inc/options/pgcache.php
pub/js/options-validator.js

If an attempt to save invalid regex value to config is made - fail to save it.
that will prevent warnings in "PgCache_ContentGrabber.php on line 946" on runtime

protection from invalid regex in reject.uri option, fixes #142

---

lib/Minify/Minify.php

This enables  image optimizers such as ShortPixel Adaptive Images to dynamically replace the background-image URLs in the W3 Total Cache cached versions of the CSS file, eliminating the need for another level of caching.
Fixes https://github.com/W3EDGE/w3-total-cache/issues/146

Apply a filter on the minified content - w3tc_minify_css_content

---

Generic_Plugin.php
lib/Minify/Minify/HTML.php
lib/Minify/Minify/IgnoredCommentPreserver.php
readme.txt
w3-total-cache-api.php
w3-total-cache.php

- Avoid PREG_JIT_STACKLIMIT_ERROR. Fixes #190
- Prevent warning on an empty needle. Fixes #203
- Allow to specify URIs with a query string in _Additional Pages_
- _Performance->Page Cache->Additional Pages_ parameter wasnt processing
- URIs with querystring correctly and didn't purge such pages when _Cache URIs with querystring_ option enabled
- Do not issue w3tc-repeat redirect when cli command executed.  Fixes #182
- Attempt to switch config is made instead.
- It may not work well for all possible cases since wp is partially initialized, but works for many

Release 0.14.2

---

Generic_Plugin_Admin.php

fix console error
document.getElementById("w3tc_monitoring_score") is null 
when adminbar is hidden and pagespeed module is active

fix console error, fixes #232

---

PageSpeed_Api.php
PageSpeed_Plugin_Widget.php
PageSpeed_Widget_View.css
PageSpeed_Widget_View.js
PageSpeed_Widget_View.php
PageSpeed_Widget_View_FromApi.php

Google Page Speed dashboard widget was using v1 api version which is obsolete now.
Showing more relevant webvitals metrics in a dashboard now.

update to pagespeed api v5, show webvitals metrics, fixes #192

---

Root_AdminActivation.php

activation was supposed to be wpadmin-only operation and didnt call full
environment update since wp-admin request was doing it right after ui
plugin activation.
but its possible to activate via wp-cli now too.

activation wasnt handing environment changes. fixes #251

---

BrowserCache_Environment.php

Apache should always set HSTS headers, not only for 2xx HTTP codes.
The `Strict-Transport-Security` header in Apache should always be sent if configured.  Without `always` in the `Header` line redirects and errors will not include the header.

Always set HSTS header if configured.  Fixes #257

---

Util_Activation.php

The exception method name was incorrect in the call from the activation, which prevented the message from being printed in the admin notice.
To replicate the issue, delete W3TC, create a new file `wp-content/advanced-cache.php`, install and activate W3TC.  You will see an admin notice with a fatal error message and a reactivate button, but it does not say what happened or how to fix it.
After the fix, the message and fix button is displayed.

Fixed typo in activation file conflict exception message method name.

---

lib/Minify/Minify/CSS/Compressor.php

regexp whose intend is to remove spaces in css selectors like
".my-class > img" was selecting beyond selector definition and catching
will the last css element.
So spaces in calc() in all except last css declaration were trimmed out
img {
height: calc(1px + 1px);
}
a {
}

removal of spaces in calc was breaking css, fixes #287

---

ConfigCompiler.php
ConfigKeys.php
Minify_AutoCss.php
Minify_AutoJs.php
Minify_ConfigLabels.php
Minify_MinifiedFileRequestHandler.php
Util_Admin.php
inc/options/minify.php

Hi there,
I've added the option to minify CSS and JS without combining which fixes #170.
However, is there a way to map the values from the current config key to the new config key after a plugin update? 
For example if the current value of `minify.css.combine == true`, I would like to set the intital value of `minify.css.method = 'combine'` else `minify.css.method = 'both'`. And at the same time how can we deprecate or remove `minify.css.combine`.
Can the authors (or other contributors) provide some input on this.
**Benefits**
Fixes #170, benefits described in the issue.
**Future PRs**
- Allow ignoring .min.js and .min.css when minify only.

Add option to minify only for both JS and CSS in auto mode

---

BrowserCache_Plugin.php

Browser cache's querystring ("Prevent caching of objects after settings
change" option) wasnt added for resources added without quotes.
Since HTML Minify removes quotes - it didn't work when HTML Minify
enabled.

BC's querystring wasnt added, fixes #60

---

Cache_Memcache.php
Cache_Memcached.php

meta tags are not parsed by browsers directly, but by apps, which seems do it violating W3C and fail to parse valid HTML without quotes.
WhatsApp is noted multiple times before acting bad in this case.
Google is not confirmed yet, even opposite - we have a lot of examples where meta tags don't have quotes and they are parsed well by google. There should be something else / more specific than just a quote for meta description tag.
It looks relevant trade-off in such situation to exclude meta tag from quotes removal optimization.
Negative effect is that websites with a lot of meta-tags, i.e. those implementing microdata and doing that meta-option way may have a lot of such. It's not so popular way at the moment.

Dont remove quotes around meta tags, fixes #187

---

PgCache_Flush.php

it's assumed as current request url by _get_page_key whats not what purging code expects.

avoid warning when someone send empty url for purging. fixes #300

---

Cache_Redis.php

In redis 6 (and possibly earlier), calling SETEX with an expiry of 0 seconds is invalid.  When $expire is 0, call SET instead.

Do not use Redis SETEX when expire=0

---

BrowserCache_Environment.php
inc/mime/other.php
ini/apache_conf/mod_expires.conf
ini/apache_conf/mod_mime.conf

At the moment W3TC doesn't support Browser Cache via .htaccess for video/ogg files. The pull request solves this. 
Therewith the expiring header is also set for those video files.

Add video/ogg support for browser chaging

---

lib/Azure/GuzzleHttp/Handler/CurlFactory.php

PHP Warning: count(): Parameter must be an array or an object that implements Countable in /home/landscape/public_html/wp-content/plugins/w3-total-cache/lib/Azure/GuzzleHttp/Handler/CurlFactory.php on line 67
https://wordpress.org/support/topic/parameter-must-be-an-array-or-an-object-that-implements-countable-w3-total-cach-2/

 Parameter must be an array or an object that implements Countable

---

Util_PageUrls.php

Required by the [get_pagenum_link](https://developer.wordpress.org/reference/functions/get_pagenum_link/) filter. Otherwise fails with:
```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function {closure}(), 1 passed in /wp-includes/class-wp-hook.php on line 287 and exactly 2 expected in /wp-content/themes/.../functions.php:684
Stack trace:
#0 /wp-includes/class-wp-hook.php(287): {closure}()
#1 /wp-includes/plugin.php(212): WP_Hook->apply_filters()
#2 /wp-content/plugins/w3-total-cache/Util_PageUrls.php(514): apply_filters()
#3 /wp-content/plugins/w3-total-cache/Util_PageUrls.php(458): W3TC\Util_PageUrls::get_pagenum_link_admin()
#4 /wp-content/plugins/w3-total-cache/Util_PageUrls.php(77): W3TC\Util_PageUrls::get_pagenum_link()
#5 …
```

do get_pagenum_link filter with both args

---

ConfigKeys.php

We should probably mirror WP core with this behavior. Their developers are confident enough to make the `comment` group persistent: https://github.com/WordPress/WordPress/commit/1f2635d52b34c2a3df967135a20c12f415299103

Don't persist the 'comment' object cache group by default

---

lib/Minify/Minify/HTML.php

spaces should be removed around display:block <li> tags which are they
by default, but that specific tag is often used for menus with
display:inline-block, when spaces around tags matter.

dont remove spaces around <li> tags since it's often inline-block, fixes #273

---

FeatureShowcase_Plugin_Admin.php
Generic_Plugin_Admin.php
SetupGuide_Plugin_Admin.php
Util_Ui.php

The buttons in the Feature Showcase are broken in a multisite installation.  They point to the default blog site instead of the network admin.  There were also a couple of links in the Setup Guide wizard with the same issue.  All were fixed by changing `admin_url()` to `network_admin_url()`, which internally checks for `is_multisite()`.

Fix admin URLs for multisite installs.  Fixes #357

---

ConfigKeys.php
Minify_ContentMinifier.php
Minify_MinifiedFileRequestHandler.php
Util_Environment.php
inc/options/general.php
inc/options/minify.php
lib/Minify/Minify/Build.php
lib/Minify/Minify/CSS.php
lib/Minify/Minify/CSS/UriRewriter.php
lib/Minify/Minify/Controller/Files.php
lib/Minify/Minify/Controller/Groups.php
lib/Minify/Minify/Controller/MinApp.php
lib/Minify/Minify/Controller/Version1.php
lib/Minify/Minify/HTML/Helper.php
lib/Minify/Minify/HTMLTidy.php
lib/Minify/Minify/ImportProcessor.php
lib/Minify/Minify/Lines.php
lib/Minify/Minify/Source.php

This fix addresses the issue of an incorrect server document root, broken loading for PHP Tidy, and a CDATA wrapper that caused syntax errors.
To simulate an incorrect server document root path, use the following code in `wp-config.php`:
```
$_SERVER['DOCUMENT_ROOT'] = '/var/www/html';
```

Fix issue 6

---

PgCache_Environment.php

Resolves #374 
- picks the first server if there
- I tried using the upstream module but unfortunately it requires http context outside the server block.

fix hardcoded nginx memcached_pass

---

BrowserCache_Page_View_SectionSecurity.php

There were a bunch of missing text domains and some phpcs items.
Some of the changes were requested in https://wordpress.org/support/topic/add-w3-total-cache

Fix browser cache settings text domains

---

CdnEngine_CloudFront.php
CdnEngine_Mirror_CloudFront.php
CdnEngine_S3.php
Cdn_RackSpace_Api_Cdn.php
Cdnfsd_CloudFront_Engine.php
Cdnfsd_CloudFront_Popup.php
Enterprise_SnsBase.php
Extension_CloudFlare_Plugin.php
Util_File.php

Resolves #399
If the administrator doesn't configure AWS credentials, fall back to the
default credential provider.  This is especially useful when WordPress
is running within EC2, as the default provider is compatible with the
AWS best practice of manging applications' IAM permissions through
instance profiles instead of hardcoded credentials.

Allow use of default AWS credential provider

---

PgCache_Plugin.php

- checks if wp cli is present and returns
- solution based on my comment https://github.com/W3EDGE/w3-total-cache/issues/305#issuecomment-869040233
- fixes #305

Prevent redirects coming from wp-cli

---

PgCache_ContentGrabber.php

is_404() not always means its really a 404 response.
real behavior may be modified hooks, and opposite.
its more correct to define logic based on real http status response code
(it wasnt available before php54).

determine if response is 404 based on headers as a priority, fixes #42

---

CdnEngine_Mirror_CloudFront.php

Hi as discussed in issue #446 
Reverts W3EDGE/w3-total-cache#435
removing async,
I will pull request in next days a change using the invalidation queue

Revert "Update CdnEngine_Mirror_CloudFront.php"

---

Extension_ImageService_Api.php
Extension_ImageService_Plugin_Admin.js
Extension_ImageService_Plugin_Admin.php
Licensing_Plugin_Admin.php

This fixes response messages when the API server reports that a rate-limit (hourly or monthly) has been exceeded for image submissions.

Fix Image Service responses and handle API rate-limit

---

Extension_ImageService_Plugin_Admin.php
Util_WpFile.php

This can be tested by changing the defined WP_Filesystem type in `wp-config.php` using **one** of the following definitions::
```
define( 'FS_METHOD', 'direct' );
define( 'FS_METHOD', 'ssh2' );
define( 'FS_METHOD', 'ftpext') ;
define( 'FS_METHOD', 'ftpsockets' );
```

Check filesystem and provide better messaging

---

Cache_Redis.php
ConfigKeys.php
DbCache_Core.php
DbCache_WpdbInjection_QueryCaching.php
Extension_FragmentCache_WpObjectCache.php
Minify_Core.php
Minify_MinifiedFileRequestHandler.php
ObjectCache_WpObjectCache_Regular.php
PgCache_ContentGrabber.php
Util_ConfigLabel.php
inc/options/parts/redis.php
inc/options/parts/redis_extension.php

Potential fix for server timeout resulting in 500 error if Redis connection/request takes too long to execute for what is allocated by the server

Fix for Redis timeout resulting in 500 error

---

ConfigKeys.php
Extension_ImageService_Page_View.php
Extension_ImageService_Plugin_Admin.php
Root_Loader.php

An option is added to choose the behavior of hiding converted image attachments via WP_Query filters.  By default, the converted images are never shown, unless the plugin is deactivated.  The new option allows them to be shown all of the time or only when the Image Service extension is active.

Add visibility option.  Fixes #476.

---

PgCache_ContentGrabber.php

wp doesnt add slashes to request_uri, so unslashing it deforms real value

wp doesnt add slashes to request_uri

---

qa/env/scripts/init-box/templates/Vagrantfile.erb

now ip is effectively hardcoded, so better to use it
https://www.virtualbox.org/manual/ch06.html#network_hostonly
"On Linux, Mac OS X and Solaris Oracle VM VirtualBox will only allow IP
addresses in 192.168.56.0/21 range to be assigned to host-only
adapters."
other ips still can be used, but needs much more local-env configuration

vitrualbox docs say it hardcoded vboxnet for 192.168.56.x

---

Cache_Redis.php
ConfigCompiler.php
ConfigKeys.php
DbCache_Core.php
DbCache_WpdbInjection_QueryCaching.php
Extension_FragmentCache_Plugin.php
Extension_FragmentCache_WpObjectCache.php
Generic_AdminActions_Test.php
Minify_Core.php
Minify_MinifiedFileRequestHandler.php
ObjectCache_WpObjectCache_Regular.php
PgCache_ContentGrabber.php
Util_ConfigLabel.php
inc/options/parts/redis.php
inc/options/parts/redis_extension.php
languages/w3-total-cache.pot
pub/js/options.js

Adds on to https://github.com/W3EDGE/w3-total-cache/issues/67 to include the option of _not_ verifying the redis server's TLS certificate when connecting over TLS.
This option is needed when connecting to a redis server configured to use TLS with self-signed certificates. In particular, [Heroku Redis](https://devcenter.heroku.com/articles/connecting-heroku-redis#connecting-in-php) falls under this category.
With this new option TLS certificates continue to be verified by default, but users who need to now have the option of disabling certificate verification.
While working on this, I noticed [this comment from the PR where TLS support was added](https://github.com/W3EDGE/w3-total-cache/issues/67#issuecomment-828548567), so I also updated the UI string to include a hint about how to use …

Redis: support connecting to servers using TLS with self-signed certificates (e.g., Heroku Redis)

---

PgCache_ContentGrabber.php
PgCache_Environment.php
qa/lib/w3tc.js
qa/tests/pagecache/trailing-slash.js

add separate entry for bla and bla/ pages, so that 301 redirects may be issued by wp for variants with/without
slash. that makes google happier

add separate entry for bla and bla/ pages, fixes #250

---

DbCache_WpdbInjection_QueryCaching.php

- Fix DB Cache causes infinite loop when using db-cluster-config.php in non-network mode
See: https://github.com/W3EDGE/w3-total-cache/issues/508

fix: DB Cache infinite loop when using `db-cluster-config.php`

---

FeatureShowcase_Plugin_Admin.php

In the Feature Showcase, the "Activate" button for the Image Service is not added if the extension is not active on a single-site install (most common).  This fix will restore the button as it was in 2.2.1.

Fix the Image Service activate button in Feature Showcase

---

Cache_Redis.php
inc/options/parts/redis.php
inc/options/parts/redis_extension.php

I'm currently getting:
```
PHP Warning:  Redis::pconnect() expects at most 5 parameters, 6 given
```
on a server running PHP 7.2 with phpredis 3.1.1 (via php72-pecl-redis).
I'm thinking this is due to phpredis introducing the additional parameters only in later versions. As such, this now version checks for phpredis newer than 4 (so all of v5 and newer) to use what W3TC already had while it reduces the parameters by 1 if it's an older version.
Of course, this can be updated/adapted to be more granular (ex. expand on this to add context support for that specific phpredis version where that support was added) and/or be implemented in a better way overall.
I've also posted this on the WP.org support forums here: https://wordpress.org/support/topic/php-warning-about-pconnect-expecting-at-most- …

Avoid PHP warning about pconnect() expecting at most 5 parameters with 6 given on some setups (likely using an older phpredis)

---

inc/options/pgcache.php

The setting login was reversed in 2.2.2.  See https://github.com/W3EDGE/w3-total-cache/blob/2.2.1/inc/options/pgcache.php#L337 vs https://github.com/W3EDGE/w3-total-cache/blob/2.2.2/inc/options/pgcache.php#L578

Fix adding max lifetime setting for Page Cache

---

Licensing_Plugin_Admin.php

Fixes error:
```
PHP Fatal error:  Uncaught ArgumentCountError: 3 arguments are required, 2 given in /var/www/html/wp-content/plugins/w3-total-cache/Licensing_Plugin_Admin.php:197
2022-07-20T07:54:31.553472336Z Stack trace:
2022-07-20T07:54:31.553475502Z #0 /var/www/html/wp-content/plugins/w3-total-cache/Licensing_Plugin_Admin.php(197): sprintf('The W3 Total Ca...', '<a class="w3tc_...')
2022-07-20T07:54:31.553477669Z #1 /var/www/html/wp-includes/class-wp-hook.php(307): W3TC\Licensing_Plugin_Admin->admin_notices('')
2022-07-20T07:54:31.553479669Z #2 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
2022-07-20T07:54:31.553481377Z #3 /var/www/html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
2022-07-20T07:54:31.553483044Z #4 …
```

fix: moving closing tag to new sprintf() param

---

Cdn_Plugin.php

This fix will apply to any users utilizing W3TC and any plugin/theme that uses wp_get_attachment_image_src with CDN enabled.
You'll need [WooCommerce](https://wordpress.org/plugins/woocommerce/) and [Variation Images Gallery for WooCommerce](https://wordpress.org/plugins/woo-product-variation-gallery/).  You'll also need a variable product.
Once you have WooCommerce and product in place, you should be able to toggle the "Host attachments" setting (on `wp-admin/admin.php?page=w3tc_cdn`) and the product page should serve local/CDN accordingly.  If my fix is working then when "Host attachments" is enabled all product images should be served via the CDN assuming they're uploaded to the bucket.

Woocommerce Variation Image Gallery plugin CDN fix

---

Cache_File_Generic.php
Util_File.php

use realpath canonicalzation to make sure no reads or writes are done
outside of cache folder.
realpath-based check is much better for security

make sure no reads or writes are done outside of cache folder

---

Cdn_Plugin.php

Reverts https://github.com/W3EDGE/w3-total-cache/pull/543 after unexpected behavior resulting from use of wp_get_attachment_image_src filter to CDN attachment URL

Revert fix for PR 543

---

Root_Loader.php

Actions and Filters added to hide the converted images generated by W3TC-IS were anonymous. This PR simply moves them to separate functions and resolves CS violations.
A response to the OP would be needed to inform them that this change has occurred and that they should be able to unhook the action/filter via functions.php
I also believe the OP could change the visibility setting from "never" to any other value to also "disable" the action/filter

Root_Loader enhancement and CS

---

inc/options/cdn/s3.php

Currently displays as: `cname.s3.amazonaws.comor CNAME`.
Proposed changes to: `cname.s3.amazonaws.com or CNAME`.

Add space between CNAME and text

---

pub/js/options.js

In reference to https://wordpress.org/support/topic/console-errors-23/
A function in `options.js` is run on non-plugin pages that expect `w3Data` to be defined.
1. Enable "Amazon Simple Storage Service (S3)" as a CDN at `wp-admin/admin.php?page=w3tc_general#cdn`.
2. Open the browser web console.
3. Go to the WordPress Plugins page -- `wp-admin/plugins.php`
4. Check for an error "Uncaught ReferenceError: w3tcData is not defined".

w3tcData is only for W3TC pages

---

Cache_File.php

Resolves warnings/errors thrown for unpack for files that are either empty or contain less than 4 bytes of data. Cached files are expected to contain at least 4 bytes of data at start that represent the cache expire time
`Warning (2): unpack(): Type L: not enough input, need 4, have 0`
**NOTE** : Unable to replicate specific error but in debugging I determined that empty/malformed files were being processed despite the malformed data

Pagecache unpack fix 

---

Cdnfsd_CacheFlush.php

A fatal error occurs when clearing all cache in the Pro version with Amazon Cloudfront as a full CDN.

Fixed cacheflush call to moved CDN default override function

---

Cache_Redis.php
ConfigCache.php
DbCache_Plugin.php
ObjectCache_Plugin.php
PgCache_Plugin.php
UsageStatistics_Sources_Redis.php
inc/options/parts/redis.php
ini/config-db-sample.php

**tl;dr:** This PR re-enables support for connecting to Redis servers using TLS with self-signed certificates. It also updates W3TC's "cache plugin config in redis" logic to support Redis servers with self-signed certificates. This updated implementation should now play nicely with older versions of `phpredis` and avoid generating [warnings about passing the wrong # of args to `pconnect`](https://github.com/W3EDGE/w3-total-cache/issues/533).
@KZeni If you're up for it, I'd love to have you test out this updated code with your setup that's using `phpredis 3.1.1`!
1. [My previous PR](https://github.com/W3EDGE/w3-total-cache/pull/494) to add support for connecting to redis using TLS with self-signed certs (e.g., Heroku Redis) was accepted on April 28, 2022 ✅ 
2. Support for disabling TLS …

Redis: reenable support connecting to servers using TLS with self-signed certificates (e.g., Heroku Redis)

---

Extension_WordPressSeo_Plugin_Admin.php
Generic_Plugin_Admin.php

To replicate simply install the Yoast SEO plugin. A dismissable admin notice should then be displayed that should have 2 buttons and a link to Yoast SEO, but without this PR only the last button is displayed

Fixed escaping issue with extenstion admin notice stripping out links

---

CacheFlush_Locally.php
Cdnfsd_CacheFlush.php
Cdnfsd_Plugin.php
Cli.php
Generic_AdminActions_Flush.php
Generic_Plugin.php
Generic_Plugin_AdminRowActions.php
PgCache_Flush.php
PgCache_Plugin.php
Varnish_Flush.php
Varnish_Plugin.php
w3-total-cache-api.php

To replicate simply disable all Purge Policy: Page Cache options under the Page Cache settings page with PageCache enabled. This will cause the top-bar menu item for Purge Modules > Page Cache: Current Page to fail to flush the given page/post

Fix top-bar purge "current page" link when PageCache purge policy disabled

---

Generic_AdminActions_Default.php

To replicate simply enable minify, navigate to the minify settings page and disable the HTTP2/push setting. Either save button should result in an infinite loop that results in a "max execution time" error

Fixed infinite loop when disabling minify HTTP2/push setting

---

ObjectCache_Plugin.php

This can be replicated by scheduling a CPT with the Object Cache enabled. Without this fix the cron job shouldn't execute. This may also apply to core pages/posts and may be correlated to issue 595

Fix for object cache not purging options and preventing cron jobs

---

Util_AttachToActions.php

This is a compound issue between the original hooks used by Page Cache not applying uniformly between regular pages/posts and custom post types and the Object Cache caching cron jobs and preventing them from executing
This PR changes the hooks so that CPTs are fully supported. A separate PR will address the Object Cache correlated issue

Fix for scheduled posts not flushing PgCache

---

Varnish_Plugin.php

The issue occurs when a post is created or modified, and the users has the reverse proxy Varnish setting enabled with Varnish installed and configured

Potential fix for parameter count fatal PHP error when using Varnish

---

PgCache_ContentGrabber.php

This applies to any configuration/engine of PgCache and doesn't appear to have any negative impact with or without this "fix". It appears to be an inconsequential configuration value in operation

Added missing PgCache configuration "host" value

---

Util_AttachToActions.php

To test this simply enable page-cache and navigate to the Comments admin page /wp-admin/edit-comments.php. Then use the quick-links under a given comment to approve/spam/trash the given comment. This should trigger the wp_set_comment_status hook and in turn flush the associated post/feed

Fix for missing on_comment_status class method.

---

DbCache_Plugin.php
ObjectCache_Plugin.php

To test this simply enable DB/Object Cache and then navigate to the Comments admin page /wp-admin/edit-comments.php. Then use the quick-links under a given comment to approve/spam/trash the given comment. This should trigger the wp_set_comment_status hook and in turn flush the associated post/feed

Remove comment status check for DB/ObjectCache

---

Cdn_AdminNotes.php
Generic_Plugin_Admin.php

Due to the fact that MaxCDN is now removed this notice will only show for users that previously configured their CDN as 'maxcdn'. The notice will inform them of the deprecation and provide a link to migrate to StackPath
One way to test is to modify Cdn_AdminNotes.php and add to line 126
`$cdn_engine = 'maxcdn';`
This should display the notice. Updating the CDN configuration to another CDN and removing the above added line should remove the notice

Added deprecation/migration admin notice for users utilizing MaxCDN

---

BrowserCache_Environment_Nginx.php
Minify_Environment.php

Fixes:
- Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /sites/en/wordpress/web/app/plugins/w3-total-cache/Minify_Environment.php on line 430
- Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /sites/en/wordpress/web/app/plugins/w3-total-cache/Minify_Environment.php on line 495
(line numbers are for latest release 2.2.12)

Fix php 8.2 depreciations

---

Util_AttachToActions.php

We were unable to replicate this within the context of a test website, but were able to generate warnings by either manually modifying Util_AttachToActions.php line 78:
`unset($data['post_status']);`
or by CLI testing using:
```
/opt/cpanel/ea-php81/root/bin/php -r '$a = array( "test" => "yes" ); var_dump( $a["nope"] === "yes" );' -d display_errors=on
Warning: Undefined array key "nope" in Command line code on line 1
bool(false)
```
See https://wordpress.org/support/topic/regression-error-on-image-upload-when-memcached-is-enabled/ for reference.

Fixed evaluations resulting in warnings/errors for non-existent values.

---

BrowserCache_Environment.php
BrowserCache_Environment_Nginx.php
BrowserCache_Page_View_SectionSecurity.php

To test simply enable the Feature-Policy / Permissions-Policy setting under Browser Cache admin page. Then set the values below that setting to one of the allowed values. Once these are set you can audit a site page request headers to determine if the Feature-Policy and Permissions-Policy headers are present and set. From there you can use a validator tool to analyze a given URL to validate the headers

Implemented Permissions-Policy

---

BrowserCache_Environment.php

The get_required_rules method features a switch that checks for the appropriate environment rules, ie apache, nginx, lightspeed, etc. This switch was missing a default which resulted in the $rewrite_rules being null if no match was found resulting in an error.
This PR adds a default switch case that will set $rewire_rules to an empty array if no environment match is found.
Reference topic: [php-error-after-upgrading-2-3-0](https://wordpress.org/support/topic/php-error-after-upgraded-2-3-0/)

2.3.0 BrowserCache Environment Rules Fix

---

Generic_Plugin_Admin.php
PageSpeed_Instructions.php
PageSpeed_Page_View.css
PageSpeed_Page_View.php
Util_PageSpeed.php

Fixed several translation related issues with grammar, broken placeholders, and an issue with script localization. Also fixed breakdown/recommendation block widths if data tables required too much space. Lastly added links to all breakdown data URLs to allow users to view the reported URL/file.
One important note, the script localization issue actually affected other scripts queued in the same manner. As it turns out the menu item title and hook suffix needed to match 100% including capitalization. All hook suffixes were lower case which caused the hooks to fail under translation. This PR will fix those as well

Multiple fixes/enhancments for PageSpeed 2.3.0

---

.travis.yml
BrowserCache_Page_View_SectionSecurity.php
composer.lock
languages/w3-total-cache.pot
qa/env/050-ssh-agent
qa/env/100-generate-envs
qa/env/scripts/init-image/600-wp-cli.sh
qa/env/scripts/restart-http.rb
qa/env/w3tc-clone
qa/tests/cdn/file-upload.js
qa/tests/cdn/pull-custom.js
qa/tests/minify/html.js
readme.txt
w3-total-cache-api.php
w3-total-cache.php

All PHPUnit tests and Travis CI checks passed.  AWS tests passed with the exception of some Litespeed tests that we'll address later.
Perform smoke tests as usual.  Additionally, test Amazon CloudFront (or anything that loads the AWS Composer dependency) on PHP versions 5.6 through 8.1, to ensure no autoloader issues.

Release 2.3.1

---

PageSpeed_Widget_View.php
inc/options/general.php

Without this fix the authorization process via the Performance -> General Settings -> PageSpeed settings section on the network administration dashboard would return with a "Sorry, you are not allowed to access this page." message upon the authorization return.

Fix for PageSpeed authroization via MultiSite installation

---

DbCache_Plugin_Admin.php
Generic_AdminActions_Test.php
Minify_Plugin_Admin.php
ObjectCache_Plugin_Admin.php
PgCache_Plugin_Admin.php
Util_Installed.php
pub/js/options.js

Fixes #448.
When testing a Memcached cache, in addition to passing the configured servers, also pass binary protocol, username and password. This allows the test to be run correctly when SASL authentication is used (when a username and password are supplied). The binary protocol option is also passed as SASL auth with Memcached requires the binary protocol to be used.

Fix Memcached test using SASL auth

---

PageSpeed_Page_View.js
Util_PageSpeed.php

Previously the GA tracking on metric toggles used the display text as the event label which for some metrics would contain displayValues that would result in variance. Subsequently the GA would show separate tracking for each variance rather than the intended general metric 
With this PR the event label should be generic for each metric

PageSpeed Google Analytics event label update

---

Minify_Plugin.php
Util_Environment.php
tests/admin/class-w3tc-admin-base-test.php
tests/admin/class-w3tc-admin-util-file-test.php
w3-total-cache-api.php

This issue occurs if the cache directory located in wp-content is moved to another location and replaced with a symbolic link. This causes both Minify and PageCache using `file` method to partially fail during the folder/file creation process in that it will only create the first element in the path i.e. `cache/minify/1/287.js` would only create the `cache` directory before failing. This would require refreshing the page or performing an admin action repeatedly until all folders/files are created
Additionally if the minify cache folder is missing it required an admin action to be performed in order for the required minify folder path to be generated which prevented minified files from being served. This appears to only occur if the minify folder fails to generate on admin action or …

Fix for symlinked cache directory causing folder/file creation to partially fail

---

Extension_ImageService_Plugin_Admin.php
Generic_Plugin_Admin.php
SetupGuide_Plugin_Admin.php
qa/env/scripts/init-box/800-w3tc.sh

This is to avoid the W3TC_DEBUG constant from switching Google Analytics to the development property.  I added a new constant check for "W3TC_DEVELOPER", which will only change the GA property ID to development.

Fix GA switch for development

---

Licensing_Plugin_Admin.php

Fixed nonce issue with the Renew Now button in the licensing expired admin notice that resulted in a 403 in the modal popup.
Without this fix, if a W3TC license expired an admin notice would be displayed at the top containing a "Renew Now" button. This button would trigger a modal containing the upgrade.php light-box template with a button linking to the checkout cart that additionally passed the relevant information to renew a license. This modal would throw a 403 due to a bad nonce in the original button and would fail to load, showing an infinite loading spinner
With this fix, the modal should now load and properly allow for a renewal to proceed

Expired license renewal admin notice Modal fix

---

DbCache_Plugin.php
ObjectCache_Plugin.php
Util_AttachToActions.php

WP deprecated the delete_blog hook in WP 5.1.0
Swapped for wp_uninitialize_site and wp_update_site which fire on site deletion and modification respectively.

Fixed delete_blog hook deprecation in WP 5.1.0

---

ConfigKeys.php
Extension_FragmentCache_Plugin_Admin.php
Extension_ImageService_Api.php
Extension_Wpml_Plugin_Admin.php
FeatureShowcase_Plugin_Admin_View.php
Generic_WidgetCommunity_View.php
Licensing_Plugin_Admin.php
UsageStatistics_Page_View_Free.php
UsageStatistics_Widget_View_Disabled.php
Util_Ui.php
inc/options/common/footer.php
inc/options/common/top_nav_bar.php
inc/options/edd/buy.php
inc/options/general.php
inc/options/parts/dashboard_banner.php
pub/css/options.css

This PR reverts all changes made to the purchase/renew buttons to restore the popup modals and iframe embeds of the cart. This allows for users to stay on-site and to automatically apply licenses on purchase

Reverted purchase/renew links back to popup modals with iframe cart

---

PgCache_ContentGrabber.php

Fix php 8.2 creation of dynamic properties.
Please check the variable type for `$_page_group` as it was a string in my case, but it could be more vast.

Fix php 8.2 deprecation

---

Generic_AdminActions_Default.php
pub/js/lightbox.js

The issue was due to the nonce value being of type array which caused the "save license" AJAX request to fail the nonce verification with a 403. This PR adds a check to ensure the nonce is a string before the AJAX request is made

Fixed issue with auto-apply failing after puchase of license

---

Cache_File_Generic.php
ConfigKeys.php
Extension_FragmentCache_Plugin_Admin.php
Util_Ui.php
inc/options/common/top_nav_bar.php
qa/env/100-generate-envs
qa/env/scripts/init-image/150-mocha.sh
qa/tests/generic/compatibility-check.js

This PR addresses several issues experienced under testing of WP 6.3 as well as a few other tests
Of note
- Puppeteer from version 1.11.0 to 2.1.1
- Page Cache disk enhanced no longer hard-expires old cache files when renamed during flush. This was causing the garbage collection under certain environments to immediately remove the old file which broke the temporary serve functionally while waiting for the new cache file
- Updated Fragment cache default settings to be inactive and simplified the activated toggle on save logic
- Various test adjustments to account for changed HTML markup IDs/classes

Fix AWS for release 2.4.0

---

Extension_FragmentCache_Plugin.php

If pro and FC activated but no engine selected under the settings block on the General Settings page, the cache.php instance method would process the FC as enabled but no engine value would exist, resulting in it defaulting to Cache_Base and throwing a warning
This PR adds to the is_extension_active_frontend check for FC to check if an engine has been selected. If none is, then FC will not process

Fixed cache.php instance warning for FC if no engine has been selected

---

Util_Environment.php

which doesn't pass config parameter

add a fallback for older version of wp-content/db.php

---

DbCache_WpdbNew.php

Declare missing class property.  Fixes #733.
Fix typos in the comments.
To test, enable DB Cache and debug for it while using PHP 8.2. Check for warnings in the PHP error_log.

Declare missing class property.  Fixes #733.

---

FeatureShowcase_Plugin_Admin.php
UserExperience_GeneralPage_View.php

This PR fixes a display issue for the General Settings block for defer scripts where a link was shown for the settings that doesn't exist if the feature isn't enabled.
This also adds the missing feature showcase block (documentation link pending)

Defer Scripts Fix

---

Generic_AdminActions_Default.php

This restores a check that was removed in the defer-scripts branch that was apparently needed for radio inputs. Without this, any settings page save that contained a radio input would fatal error

Defer Scripts Config Save Fix

---

CacheGroups_Plugin_Admin_View.js
CacheGroups_Plugin_Admin_View.php

This PR fixes several issues with the cache groups feature JavaScript as well as a few additional small tweaks
1. Added groups will now have dom events properly apply to them
2. The submit validation JS will now properly audit submissions to prevent duplicate values between group blocks
3. The cookie groups "cache" field now has a label to identify it's purpose

Fix Cache Groups JS

---

BrowserCache_Environment_Nginx.php
Mobile_Base.php

Fixed https://github.com/BoldGrid/w3-total-cache/blob/2.4.1/BrowserCache_Environment_Nginx.php#L346-L352 where lines should be added into the rules array and not concatenating a string.
Fixed incorrect class property name at https://github.com/BoldGrid/w3-total-cache/blob/2.4.1/Mobile_Base.php#L13 to what is used at https://github.com/BoldGrid/w3-total-cache/blob/2.4.1/Mobile_Base.php#L23

Fix Nginx rules and php 8.2 deprecated error

---

Util_Ui.php

Warning thrown by null key value passed to Util_Ui::config_item call
https://github.com/BoldGrid/w3-total-cache/blob/366ec47fcc7691614b9a14583fb47528b045ceb1/Extension_ImageService_Page_View.php#L110C1-L132C3

Fixed PHP8+ warning for image service extension.

---

inc/options/cdn/azure.php

There is a missing space between the configured FQDN and the word or.
Please have a look at the attached screen shoot

Fixing visual bug related to missing space

---

Generic_AdminActions_Flush.php

Before this fix, clicking the "Purge All Caches" in the top admin bar did not clear the admin notice indicating that a flush was needed after changes were saved but no flush done. This PR should fix that

Fixed flush admin notice when flushing all via admin bar

---

lib/Minify/Minify/Cache/File.php

This is a simple fix for an edge case where a cache meta file may not be present, the cache file is present, and file locking is disabled.  I don't know the best way to test it.  Marko and I couldn't replicate it but asked the reporter to test it.

Fix fatal error in edge case.  Fixes #759

---

qa/tests/generic/referrer-groups-theme.js
qa/tests/generic/user-agent-groups.js
readme.txt
tests/admin/class-w3tc-admin-base-test.php
w3-total-cache-api.php
w3-total-cache.php
yarn.lock

This release branch is to bump the version to 2.6.0 and update tests and NodeJS dependencies.  Travis CI is passing.  AWS passes.

Release 2.6.0

---

CdnEngine_Mirror_BunnyCdn.php
Cdn_BunnyCdn_Api.php
Cdn_BunnyCdn_Popup.php

To test, enable Bunny CDN for static assets.  You do not have to authorize the CDN to replicate the issue.  Before the update, try to upload something to the WordPress Media Library with Bunny CDN enabled.  An error message will be raised.  After applying the fix, the error will not be raised and the file will be uploaded without issue.

Fix Bunny CDN library upload

---

Cdn_BunnyCdn_Page_View.js
Cdn_BunnyCdn_Page_View.php

Adds the ability to change the Bunny CDN custom hostname used when rewriting asset URLs on pages.  It does not change anything at Bunny.Net.
See https://github.com/BoldGrid/w3-total-cache/issues/768
Fixes #768

Allow Bunny CDN custom hostname changes

---

Extension_CloudFlare_Api.php
Extension_CloudFlare_Page_View.php

See https://github.com/BoldGrid/w3-total-cache/issues/770
The numeric values should be passed to the Cloudflare API as integers.
The Max Uploads value must be one of the accepted values.

Fixes #770

---

BrowserCache_Environment_Nginx.php

See https://wordpress.org/support/topic/feature-policy-permissions-policy-issue-with-nginx/
To test, set the `Feature-Policy` and `Permissions-Policy` headers in the Browser Cache Security Headers section (`wp-admin/admin.php?page=w3tc_browsercache`) when using Nginx as a web server.  Review the generated "nginx.conf" file in the WordPress ABSPATH directory.

Fix Nginx feature and permission policy header syntax

---

Util_Installed.php

After upgrading my website from PHP 7.4 to PHP 8.2, memcache was not available anymore. But W3 Total Cache was configured to use memcache. 
This error happened : 
To fix this issue, I add two more checks to `$test_value['content']`

:bug: Fix memcache check

---

inc/options/cdn.php

To test:
1. Configure Amazon CloudFront as a CDN for objects.
2. Go to `wp-admin/admin.php?page=w3tc_cdn`
3. Click the "Purge" button.
4. See a popup modal.

Fix CloudFront purge button

---

Generic_Page_Install.php

When `Util_Rule::can_check_rules()` returns `false` (as it does on the Caddy web server,) `$other_areas` is left undefined which causes an uncaught type error on https://github.com/BoldGrid/w3-total-cache/blob/f043f6eb1d4c3a8327b8c63867a4d37296c94dff/inc/options/install.php#L281
This change has `$other_areas` behave the same as `$rewrite_rules_descriptors`.

Fixes an uncaught type error on the Install page.

---

FeatureShowcase_Plugin_Admin.php
Generic_Plugin.php
Generic_Plugin_Admin.php
UserExperience_DeferScripts_Page_View.php
UserExperience_GeneralPage_View.php
UserExperience_Plugin_Admin.php
UserExperience_Preload_Requests_Extension.php
UserExperience_Remove_CssJs_Extension.php
UserExperience_Remove_CssJs_Mutator.php
UserExperience_Remove_CssJs_Page_View.js
UserExperience_Remove_CssJs_Page_View.php
Util_Ui.php
inc/options/common/footer.php
pub/css/options.css

To test, navigate to the _General Settings -> User Experience_ and enable the _Remove Unwanted/Unused CSS/JS_ option. Then navigate to the _User Experience_ settings page where you should see 2 new metabox sections labeled _Remove CSS/JS Everywhere_ and _Remove CSS/JS Individually_.
The _Remove CSS/JS Everywhere_ is very simple in that you define relative/absolute file paths for CSS/JS that you wish to remove site-wide. These match on partial so it could be as simple as the file name
The _Remove CSS/JS Individually_ functions similarly to the cache groups in that you click the Add button and define a target CSS/JS file path you wish to remove. Once created it should focus on a textarea where you can define relative/absolute page/post URLs that the target CSS/JS file will be removed from. …

Add Remove CSS/JS feature

---

Util_Ui.php

On general settings page, the Save Settings button was missing the ID attribute due to the code not applying the $b1_id as the ID. This simple PR addresses that. Testing the save appears to work and no obvious functionality or CSS issues occur as a result of the added ID

Small fix for config save split button missing ID attribute

---

Extensions_Page.php
inc/options/extensions/list.php

On the extensions page, the All, Active, and Inactive counts were incorrect due to internal non-public "extensions" being counted. This PR filters those out so the counts are correct on the extensions page

Fixed exentions count(s) on Extensions page

---

UserExperience_LazyLoad_Mutator_Unmutable.php
lib/Minify/Minify/CSS/Compressor.php
lib/Minify/Minify/Cache/File.php
lib/Minify/Minify/HTML.php

Fixes a couple `Creation of dynamic property is deprecated` errors.
Question: Should the libs be fully updated instead of locally modified? If so, they should be moved to composer in my opinion. 
To keep impact low I chose to only fix the deprecation warnings for now.

#793 Fix deprecation errors dynamic property assignment

---

PageSpeed_Page.php
PageSpeed_Widget.php

This PR simply changes the PageSpeed data option to not autoload on WordPress startup. It should now only load on demand on pages that require it

Changed PageSpeed data to not be autoloaded

---

CacheGroups_Plugin_Admin.php

In the Cache Groups section, if user agents/referrers contained spaces, these would be placed in the htaccess file without being properly escaped which would break the entire site. This PR simply escapes those spaces

Cache Groups - Fixed white space htaccess issue

---

Generic_Plugin.php

Without this PR change the w3tc_processed_content filter will not apply if PageCache is enabled
Add this to the theme's functions.php to test
`function modify_processed_content( $buffer ) {
return $buffer . "
/**
* test w3tc_processed_content filter 2
*/
";
}
add_filter( 'w3tc_processed_content', 'modify_processed_content' );`
This PR moves the do_obj_callback call for pagecache after the filter which appears to allow the filter to apply

Fix issue with w3tc_processed_content filter

---

PgCache_Environment.php

This PR simply modifies the apache rules for PageCache so the Accept-Encoding applies for both brotli and gzip if both are enabled. Previously if both were enabled only brotli would apply

PageCache Brotli & Gzip 

---

Cache_File_Generic.php
Extension_FragmentCache_WpObjectCache.php

This PR simply adds a return to the flush method for fragment cache which indicates that it returns a boolean but previously didn't return anything.

Added return value for flush method.

---

CdnEngine_CloudFront.php
CdnEngine_S3.php
Cdn_Core.php
inc/options/cdn/cf.php
pub/css/options.css
pub/js/options.js

Fixes https://github.com/BoldGrid/w3-total-cache/issues/845
This enhancement also adds a display span for the effective hostname, visible on the settings page.
To test:
- Create or have an existing Cloudfront distribution using an S3 bucket for storage in the "us-east-1" default region.
- Enter the CDN details in the CDN Cloudfront S3 push configuration.
- Use the test button to see that it passes for both US East selections for "bucket".

us-east-1 (default region) is not used in the Cloudfront hostname

---

Generic_AdminActions_Test.php
inc/options/parts/redis.php

To test:
1. Configure Page Cache to use Redis.
2. Go to `wp-admin/admin.php?page=w3tc_pgcache` and click the test button.
3. See the test pass.
4. Change the server IP and/or port number to something else/invalid.
5. Click the test button.
6. See the test fail.
I also fixed the example port number in the description.

Fix Redis test

---

Extension_ImageService_Page_View.php
Generic_Plugin_Admin.php
UserExperience_GeneralPage_View.php
UserExperience_Remove_CssJs_Extension.php
UserExperience_Remove_CssJs_Page_View.php
Util_Ui.php
inc/options/general.php
pub/css/options.css

This PR updates the config_item_xxx methods to include new options for "score" and "score_description" that will display a new block under the setting description that shows as
This also addresses a minor display issue with certain config_item_xxx methods displaying inappropriately for phone resolutions

Remove CSS/JS Upsell

---

PgCache_Plugin.php
PgCache_Plugin_Admin.php
inc/options/pgcache.php
pub/js/options.js

This PR addresses some issues with the Handle XML and Cache Feeds settings
Specifically it:
- Removes the JS that auto-toggles Handle XML if Cache Feeds is enabled/disabled
- Fixes the auto-toggle on save that occurs in the background where it enables Handle XML if Cache Feeds is enabled (won't auto-disable if Cache Feeds is disabled afterwards)
- Removes the "slows down cache" in Handle XML description
- Moves the Handle XML setting from the bottom of the Advanced block to the General block under the Cache Feeds setting
We had discussed the possibility of making Handle XML enabled by default or even remove the setting and have the plugin always handle the XML mime type...but after speaking with Max it was decided to leave as is due to concerns about it slowing down the cache (albeit …

Handle XML and Cache Feeds settings tweak

---

UsageStatistics_Page.php

When the statistics page is viewed either as a free user or with the feature disabled, the chartjs.min.js was loaded and resulted in JS errors. This PR just adds a condition check to prevent loading the JS file if the user is free or the feature is disabled

Google Chart JS Error Fix

---

PgCache_Plugin_Admin.php

This PR simply changes the cleanup_local method which calls the Cache_File_Cleaner_Generic under the Disk: Enhanced engine to use the PageCache Lifetime setting instead of the Browser Cache HTML Lifetime setting
Additionally, I've reviewed the Garbage Collection process and it appears that it does use the PageCache Garbage Collection Interval setting and will both rename expired cached files to _old and remove expired _old files
```
function _clean( $path, $remove = false ) {
$dir = false;
if ( is_dir( $path ) ) {
$dir = @opendir( $path );
}
if ( $dir ) {
while ( ( $entry = @readdir( $dir ) ) !== false ) {
if ( $entry == '.' || $entry == '..' ) {
continue;
}
$full_path = $path . DIRECTORY_SEPARATOR . $entry;
if ( substr( $entry, -4 ) === '_old' && !$this->is_old_file_expired( $full_path ) …
```

Fixed PageCache File Cleaner using wrong expire value

---

.gitignore
.travis.yml
Minify_Plugin.php
composer.json
composer.lock
package.json
phpunit.xml
qa/env/100-generate-envs
qa/env/scripts/init-image/150-mocha.sh
qa/env/scripts/init-image/200-db.sh
readme.txt
tests/admin/class-w3tc-admin-base-test.php
w3-total-cache-old-php.php
w3-total-cache.php
yarn.lock

I raised the minimum PHP version to 7.2.5, updated Composer and NodeJS dependencies, adjusted the PHPUnit, Travis CI, and Puppeteer configurations, removed the video in the readme file, fixed some PHPUnit tests, and fixed some PHP 8 warnings that were raised in tests.

Bump minimum PHP and update dependencies

---

UserExperience_GeneralPage_View.php
UserExperience_Remove_CssJs_Page_View.php
Util_Ui.php
inc/options/general.php
inc/options/pgcache.php
pub/css/options.css

This PR adds a proof block for the REST API Caching feature under Page Cache -> REST API section
Additionally this PR adds the option to add score blocks to radiogroups if values are configured as pro, as well as making the score block label configurable

Added proof block for REST API caching

---

Cdn_GeneralPage_View.php
ConfigKeys.php

To test:
1. Select StackPath as the CDN and save settings.
2. See the notice above the selection.
New installations will default to no CDN selected.
Ref: https://github.com/BoldGrid/w3-total-cache-internal/issues/1814

Update StackPath message and CDN default to none

---

UserExperience_Remove_CssJs_Extension.php
UserExperience_Remove_CssJs_Page_View.php
Util_Ui.php

When no singles are defined, the singles block would throw an error when displaying due to how it saves a completely blank section. A check was added to skip processing if the sub-config wasn't an array
This PR also addresses a PHP warning that is thrown for textarea settings that were blank and removes some duplicated hook calls for the Remove CSS/JS feature

Remove CSS/JS error/warning fixes

---

PgCache_ContentGrabber.php

analyze headers in a case-insensitive way
http headers are case-insensitive according to rfc2616, Section 4.2 but plugin was analyzing them in a most-common way they are sent.
some environment / code use different case and headers-based functionality was stopping to work.
examples: redirects caching, handling of xml content, when headers are sent in other than expected case.

analyze headers in a case-insensitive way

---

inc/options/minify/css.php

This PR adds the score block config for **Minify -> CSS -> Minify engine settings** for the Eliminate Render Blocking CSS option

Added GPS proof for Minify Eliminate Render Blocking CSS

---

Cache_Redis.php

Reported in https://wordpress.org/support/topic/persist-deprecation-error-on-php/
The reported error when using PHP 8.1 was:
```
PHP Deprecated:  Redis::connect(): Passing null to parameter #2 ($port) of type int is deprecated in wp-content/plugins/w3-total-cache/Cache_Redis.php on line 525
```
Uses an integer instead of a null value for the port parameter.
To test,:
1. Configure Redis to listen on a UNIX socket and a port.
2. Configure Page Cache to use Redis.
3. Go to the `wp-admin/admin.php?page=w3tc_pgcache#advanced` page and test the socket with `unix:/tmp/redis.sock` or whatever was configured in Redis.
4. See "Test passed."

Fix Redis connect port for unix sockets

---

inc/options/common/footer.php

This update replaces the embedded MailChimp form with a link to a sign-up page on our website -- https://www.boldgrid.com/w3-total-cache/newsletter-signup/
To test: Review the footer and test the link.

Replace MailChimp form with a sign-up link

---

Cli.php
Config.php

- Fixed the WP-CLI option output to escape properly.
- Added a new "json" type for the "option get" and "option set" that outputs valid JSON.
- Applied PHPCS WPCS and formatting.
- Added "w3tc" as a WP-CLI command alias.
Fixes #31
Example commands:
```
wp w3tc export export.json
wp w3tc export export.json --mode=0400
wp w3tc option set test '{"testing": true, "extra": "stuff..."}' --type=json
wp w3tc option get test --type=json
```

Fix WP-CLI option output and more

---

Extension_ImageService_Api.php
Extension_ImageService_Plugin_Admin.php

You can now get the Image Service usage and limit data from `Extension_ImageService_Plugin::get_api()->get_usage();`.  If you need fresh data, then pass a boolean: `Extension_ImageService_Plugin::get_api()->get_usage( true )`.
The data is now stored in a transient for 1 day.  The settings page gets transient data if it exists.

Add image service limits and update transient usage

---

UserExperience_GeneralPage_View.php

This PR adds the missing proof block on the General Settings page under the User Experience section for the lazy load google maps setting

Lazy Load Google Maps Proof

---

Util_AttachToActions.php

See https://wordpress.org/support/topic/util_attachtoactions-trash-medias-conflict/
By default, WordPress deletes media.  To trash media instead, add the following to `wp-config.php`:
```
define( 'MEDIA_TRASH', true );
```
To test, trash a media item.  Before the fix, an error message "Error in moving the item to Trash." was displayed.

Fix pre_trash_post return

---

Generic_Plugin_AdminNotices.php

This prevents the class from retrieving notices on every page load.

Dismissible notices: Reduce execution

---

Generic_Plugin_AdminNotices.php

When the API2 server returns a non-200 HTTP status, the message is usually something like the following:
```
<p>There has been a critical error on this website.</p>
<p>
<a href="https://wordpress.org/documentation/article/faq-troubleshooting/">Learn more about troubleshooting WordPress.</a>
</p>
```
The admin-ajax call does not return the actual markup returned; it sends JSON like the following:
```
{"message": "server error"}
```
... which is valid JSON, so the method continues and expects a certain structure that does not exist and hits a fatal error.
```
PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in wp-content/plugins/w3-total-cache/Generic_Plugin_AdminNotices.php:142
```
I noticed this issue when the development API2 MySQL server was down.

Check API2 status for non-200

---

DbCache_Plugin.php
ObjectCache_Plugin.php
Util_AttachToActions.php

This update better handles the flushing of Page, Object, and Database caches on certain actions.
Fixes #929
To test:
1. Enable Page, Object, and Database cache on a multisite installation.
2. Create a test blog site.
3. Browse around in incognito/private browsing to build cache objects.
4. Delete the test blog site.  Caches should flush.
5. On any WordPress installation, repeat step 3 and each of the following actions:
a. Switch theme.
b. Create or edit a nav menu item.
c. Take action to create or edit a taxonomy term.
d. Take action to delete a taxonomy term.

Flush better on actions

---

SetupGuide_Plugin_Admin.php

fixes #359 
1. Navigate to the Setup Guide
2. On the Welcome step there is more information for if a caching method is unavailable

Setup Guide - Why are some options unavailable? - issue-359

---

pub/css/options.css

Fixes [internal-1816](https://github.com/BoldGrid/w3-total-cache-internal/issues/1816)
- Suppot link in the admin menu is now blue instead of red.

Update support link color in admin bar and menu

---

PageSpeed_Api.php
PageSpeed_Instructions.php
inc/options/general.php

This PR migrates the authorization process for Google PageSpeed insights to the API server for better security
To test, simply authorize GPS feature and then revoke. The access key should expire after 24hours and should automatically renew

GPS Fix - Plugin

---

PgCache_Plugin_Admin.php

This PR addresses a PHP warning that is thrown if the usage statistics data becomes stale

Statistics Widget Warning Fix

---

Generic_WidgetAccount_View.php

This PR simply adds another case for "active.by_ip" for the license status in the Account widget on the Dashboard

License Status Fix

---

Extension_Wpml_Plugin_Admin.php

From https://github.com/BoldGrid/w3-total-cache-internal/issues/1803.
Install and activate https://wordpress.org/plugins/translatepress-multilingual/ to see if the WPML extension can now be activated.

Update WPML extension requirements for TranslatePress

---

Extension_ImageService_Plugin_Admin.php
Util_Environment.php

To test, add a "Deny from <ip_address>" for the server IP address to `.htaccess` and go to the Media Library page in list mode (`wp-admin/upload.php?mode=list`) with the WebP Converter active.  There will be an admin notice at the top of the page with a support link.

Add WP Cron error notice

---

Extension_ImageService_Plugin_Admin.php
Util_Environment.php

To test, add a "Deny from <ip_address>" for the server IP address to .htaccess and go to the various pages with the WebP Converter active. There will be an admin notice at the top of the page with a support link.
The WP Cron error notice is now displayed in the following places:
- Media Library (in list mode -- `wp-admin/upload.php?mode=list`)
- Add New Media File / Upload New Media (`wp-admin/media-new.php`) (only when auto-convert is enabled)
- WebP Converter settings page (`wp-admin/upload.php?page=w3tc_extension_page_imageservice`)
- Editing pages using the WordPress media tools (only when auto-convert is enabled)

Add more WP Cron error notice checks

---

Cache_File_Generic.php
Util_Rule.php
Util_WpFile.php

fixes coding standards for #680

fixed coding standards for pr-680

---

pub/js/options.js

To test, go to the General Settings and toggle the Database Cache and Object Cache engines to see when the notices are shown or hidden.  A notice is only displayed when the engine is enabled and the type is "Disk".

Update disk notice logic

---

Extension_AlwaysCached_Page_View.php
Extension_AlwaysCached_Page_View_BoxCron.php
Extension_AlwaysCached_Page_View_BoxFlushAll.php
Extension_AlwaysCached_Page_View_BoxQueue.php
Extension_AlwaysCached_Page_View_Exclusions.php
Extension_AlwaysCached_Plugin.php

This PR simply updates the UI for many of the settings to better clarify what each does. It also adds a check for if Page Cache is enabled and displays an admin notice if it's not, indicating to enable it with a link to the General Settings page

Always Cached UI Update

---

Minify_MinifiedFileRequestHandler.php

Fixes minify still logging when debug is not checked.
1. Flush cache
2. Go to the site and monitor wp-content/cache/log/000000/minify.log
3. The log file should not have any new entries.

fixes #990

---

PageSpeed_Page.php
PageSpeed_Page_View.js

This PR adds Google Tag tracking for analytics that will report data on
'mobile_score'
'desktop_score'
'mobile_first_contentful_paint_score'
'mobile_first_contentful_paint_display_value'
'mobile_largest_contentful_paint_score'
'mobile_largest_contentful_paint_display_value'
'mobile_interactive_score'
'mobile_interactive_display_value'
'mobile_cumulative_layout_shift_score'
'mobile_cumulative_layout_shift_display_value'
'mobile_total_blocking_time_score'
'mobile_total_blocking_time_display_value'
'mobile_speed_index_score'
'mobile_speed_index_display_value'
'desktop_first_contentful_paint_score'
'desktop_first_contentful_paint_display_value'
'desktop_largest_contentful_paint_score'
'desktop_largest_contentful_paint_display_value'
'desktop_interactive_score' …

Added tracking for Google PageSpeed scores

---

Generic_Plugin_Admin.php
Root_AdminActivation.php

This PR simply adds the plugin install date (technically plugin activation) which is pushed to GA as a part of the config (user properties)
This PR also fixes the pro services click event tracking to use production parameter keys (production used camel case whereas dev used underscores)

Add install date to GA4

---

Cdnfsd_GeneralPage_View.php
ConfigSettingsTabsKeys.php
Util_Ui.php
inc/options/general.php
pub/css/options.css
pub/js/options.js

Adds tutorial content for main caching types
1. Go to each of the main caching types.
2. Click on the tutorials tab
3. Review the content there 
4. Click back to general settings or premium services
5. Make sure the tabs are working correctly with hiding and showing the correct information.

Add help tabs and content

---

wp-content/object-cache.php

Added check to drop in file to prevent object cache from initializing if it is disabled but the drop in remains in place (should be removed if it is in the default location).

Object Cache Drop In Feature Enable Check

---

Util_Debug.php

To test: Enable debug logging, browse some pages, and check the logs directory path in "wp-content".

Fix logs directory name

---

Extension_ImageService_Api.php
Generic_Plugin_Admin.php
Generic_Plugin_Survey.php
Licensing_Plugin_Admin.php
PageSpeed_Api.php
Root_AdminActivation.php
Root_Environment.php
Root_Loader.php
SetupGuide_Plugin_Admin.php
Util_Environment.php
inc/lightbox/exit_survey.php
inc/options/general.php
pub/css/exit-survey.css
pub/css/lightbox.css
pub/js/exit-survey.js
pub/js/lightbox.js

To test simply navigate to the plugins page and click on the deactivate link for W3 Total Cache. It should display a popup modal with an exit survey

Exit Survey

---

Generic_Environment.php

This fixes the file check to compare the source and destination "advanced-cache.php" addin/dropin file.

Fix check for advanced-cache.php file.  Fixes #1025

---

Cdn_Plugin.php

Add PCRE_DOTALL flag to srcset regex pattern to properly match multiline srcset attributes in HTML content. This ensures CDN replacement works correctly even when srcset values span multiple lines.

fix(Cdn_Plugin.php): improve srcset regex pattern to handle multiline attributes

---

BrowserCache_Environment.php
BrowserCache_Environment_Nginx.php

This PR fixes 2 bugs in the Browser Cache Security section
- The script-src-elem setting was being overridden by the value in style-src-attr setting
- The style-src-attr setting wasn't applying

Browser Cache Security Header Fix

---

BrowserCache_Environment.php
BrowserCache_Environment_LiteSpeed.php
BrowserCache_Environment_Nginx.php
BrowserCache_Plugin.php
Minify_Environment.php
inc/options/browsercache.php

This PR adds new immutable options in the dropdowns for the cache policy select for the CSS/JS and Other/Media sections located on the Browser Cache settings page

Browser Cache CSS/JS and Other/Media Cache Policy Immutable

---

Generic_Plugin_Admin.php
pub/js/options.js
w3-total-cache-api.php

Updated the Forums API used on the General Setting page to be a PHP function to get data.

updated api to admin-ajax

---

Generic_Plugin_Admin.php
pub/js/exit-survey.js

To test:
1) Uncheck "Anonymously track usage to improve product quality" in the General Settings.
2) Deactivate the plugin.
3) See the popup modal and no console errors.
4) Check "Anonymously track usage to improve product quality".
5) Perform steps 2 and 3.

Fix survey and GA JS

---

.travis.yml
composer.json
composer.lock
package.json
phpcs.xml
yarn.lock

This updates the Travis CI configuration to use the Composer version of PHPCS.  It also attempts to fix an issue with deploying the ZIP to GitHub Releases.

Fix Travis CI and PHPCS

---

PgCache_Environment.php

This PR addresses an issue with Page Cache when using the Disk Enhanced engine under nginx where page/posts would result in an nginx 404 instead of hitting PHP when no cache entry is found

Nginx Page Cache - Disk Enhanced Fix

---

ConfigKeys.php
DbCache_WpdbInjection_QueryCaching.php
ObjectCache_WpObjectCache_Regular.php
Util_File.php
inc/options/dbcache.php
inc/options/objectcache.php

To test:
1. Save the settings and review the `master.php` configuration file for the new setting values for `objectcache.wpcli_disk` and `objectcache.wpcli_disk` are set to a default value of `false`.
2. Go to the Object Cache settings page, check the box "Enable for WP-CLI", and save the settings.
3. Review the setting to ensure that it is enabled (and set to `true`).
4. Go to the Database Cache settings page, check the box "Enable for WP-CLI", and save the settings.
5. Review the setting to ensure that it is enabled (and set to `true`).
Notes:
If one of the cache engines is disabled, the associated setting for it is also disabled on the settings page.
There is also a fix for silent warnings showing in Query Monitor in reference to database cache directories.

Add settings to enable objectcache and dbcache for WP-CLI

---

ObjectCache_Environment.php
wp-content/object-cache.php

Transients are not being retrieved when using WP-CLI.  For example, when `wp core check-update` is executed when there is an actual WordPress update pending, the resulting output is "Success: WordPress is at the latest version." when it should be something like:
```
+---------+-------------+-----------------------------------------------------------------------+
| version | update_type | package_url                                                           |
+---------+-------------+-----------------------------------------------------------------------+
| 6.7.2   | minor       | https://downloads.wordpress.org/release/wordpress-6.7.2-partial-1.zip |
+---------+-------------+-----------------------------------------------------------------------+
```
To test:
1) Visit a W3TC plugin page …

Fix WP-CLI Object Cache

---

Root_Environment.php
tests/admin/class-w3tc-admin-root-environment.php
tests/admin/class-w3tc-admin-util-environment.php

This pull request fixes the issue of deleting the W3TC WP Options when the user selects to delete data on deactivation in the exit survey.
Test:
1) Run PHPUnit to see if it passes the new test.
2) Check the database for 'w3%' options exist.
3) Deactivate the plugin with the delete checkbox checked.
4) Check the database to ensure the options were deleted.

Add phpunit tests

---

Generic_Plugin_Survey.php
inc/lightbox/exit_survey.php
pub/js/exit-survey.js

This PR makes it so if the user selects yes for data removal in the exit survey and then clicks on the "Skip & Deactivate" link it will remove plugin data

Exit Survey data delete on skip

---

UsageStatistics_Page.php

Test: Load the `wp-admin/admin.php?page=w3tc_stats` page with Statistics disabled.  Without the fix, there will be an HTTP error in Query Monitor.  Enable Statistics to see that the charts are displayed correctly.

Fix missing w3tc-canvasjs

---

PgCache_ContentGrabber.php
Root_Loader.php

There are two fixes:
- Fix cookie cache group regex matching
- Fix error in meta_query for Image Service media when run before admin_init
To test:
1. Go to the Cache Group settings page (`wp-admin/admin.php?page=w3tc_cachegroups#manage-cg`) and enable the default cookie group "loggedin" and set it to cache.
2.  Go to General Settings (`wp-admin/admin.php?page=w3tc_general`) to enable Page Cache (Disk: Enhanced).
3. Go to the Page Cache settings (`wp-admin/admin.php?page=w3tc_pgcache`) and uncheck "Don't cache pages for logged in users", "Don't cache pages for following user roles", and save the settings.
4. Open an Incognito or Private Browsing window, log in, and browse to some front-end pages.
5. View the page source to see that the W3TC footer comment contains "Page Caching using Disk: …

Miscellaneous fixes

---

CdnEngine_S3.php
CdnEngine_S3_Compatible.php

When testing Amazon S3 on Cloudfront, an error "Objects are not equal" is shown.  This fix allows it to pass.

Fix AWS S3 test

---

UserExperience_Emoji_Extension.php

Hints passed through the wp-resource_hints hook can be either a flat or associative array. Our implementation handled these values as a flat array only which caused issues when associative values were present. This PR updates our implementation to properly handle both formats

Fix wp_resource_hints hook issue in UserExperience_Emoji_Extension.php

---

Generic_Plugin_Admin.php
Root_AdminActivation.php

Fixes #1074
To test:
Replication steps are in the GitHub issue.  In order to stage the scenario, first remove the W3TC rules from your main `.htaccess` file and `chown root:root` so that WordPress cannot write to the file.
The WP_DEBUG error logging is to help debug.

Fix exception handing on activation (#1074)

---

wp-content/object-cache.php

This PR addresses a bug that was introduced in WP 6.4-6.7 where non-existent options would result in repeated cache misses if called in a loop

Avoid Redudant Cache Misses WP 6.4 - 6.7

---

FeatureShowcase_Plugin_Admin.php

This PR simply adds a feature card to the Feature Showcase for the new AI Crawler feature
The card should not show if the Extension_AiCrawler_Util::is_allowed returns false
If it does display, if the extension isn't activated then the button will be "Enable" and will link to the extensions page. If it is activated, then it will be "Settings" and will link to the settings page

AI Crawler Feature Card

---

PgCache_Plugin_Admin.php

Fixes #1163
To test:
1. Checkout the `master` branch
1. Enable Page Cache
1. Enable Cache Preload (`wp-admin/admin.php?page=w3tc_pgcache#cache_preload`) with a valid sitemap URL leading to "wp-sitemap.xml" or similar.
1. Add to "PgCache_Plugin_Admin.php" line 211: $response['body'] = '&raquo';
1. Tail the PHP error log
1. Purge the Page Cache
1. Run `wp cron event run w3_pgcache_prime`
1. See warnings
1. Revert the line added containing the invalid XML.
1. Checkout this fix branch
1. Add the line back
1. Purge the Page Cache
1. Run `wp cron event run w3_pgcache_prime`
1. See no errors logged

Discard simplexml errors

---

Extension_ImageService_Cron.php
Extension_ImageService_Plugin_Admin.php

This update fixes a filter callback return and optimizes the WP_Query calls (reduced object contents; post IDs, since we only need the IDs).
To test:
1. Enable the WebP Converted extension
2. Start tailing your error log
3. Add some images to the Media Library
4. Go to the "Total Cache WebP Converter" page (`wp-admin/upload.php?page=w3tc_extension_page_imageservice`)
5. Click "Revert All"
6. Watch the counts update
8. Click "Convert All"
9. Watch the counts update
10. Go to the Media Library and see that the images have been converted

Optimize WP_Query and fix filter return

---

Cache.php
Cdn_Core.php
Cdn_TotalCdn_Widget.php
Cdn_TotalCdn_Widget_View.css
Cdn_TotalCdn_Widget_View_Unauthorized.php
Generic_Page_Dashboard_View.css
Util_Widget.php

This PR adjusts the dashboard CDN widget logic so that if the Cloudflare extension is configured but not active, it won't show as active in the CDN widget.
This also adjusts the "Configure" link to properly link to the CDN settings or General Settings CDN metabox, depending on if a CDN is active and configured. This includes a check if the engine is Cloudflare and if the extension is active.
Lastly, this PR adjusts some CSS so that the configure link is a button and always visible.

Adjust Dashboard CDN Widget

---

AGENTS.md
Generic_Plugin.php
tests/test-generic-plugin.php

https://imh-internal.atlassian.net/browse/ENG5-524
To test:
1. Enable mfunc -- see [how-does-page-fragment-cache-work](https://github.com/BoldGrid/w3-total-cache/wiki/FAQ:-Developers#how-does-page-fragment-cache-work)
1. Ensure that Page Cache is enabled.
1. Create a test page with HTML to utilize the feature.
1. In Incognito, browse to the page and review the source.  The literal comment/code added should not be visible.
1. View the page via REST API - "/wp-json/wp/v2/pages/{post_id}".  The comment/code should be stripped out.
1. Change the branch to the latest tag and reload the REST API page.  You will see the comment/code.

Sanitize mfunc comments

---

Cdnfsd_TotalCdn_Page.php
Cdnfsd_TotalCdn_Status_Dns.php

This PR adds the DNS status test for the CDN FSD status section
To test setup with a pro license with total CDN and enable/configure FSD. This should set the hostname on save. Then update the DNS to point to the CDN
Then go to the CDN settings page and click on the Check Status button within the FSD box. It should pass. To see the failure state modify Cdnfsd_TotalCdn_Status_DNS.php to manually trigger a failure or perform the test before pointing the DNS
NOTE: This test won't run without the hostname test so may need to wait for that PR to be merged and then update this one so it has that. Or you can comment out line 132 in Cdnfsd_TotalCdn_Page.php

Added FSD DSN test

---

Cdn_TotalCdn_Api.php
Cdnfsd_TotalCdn_Page.php
Cdnfsd_TotalCdn_Status_Dns.php
Cdnfsd_TotalCdn_Status_Ssl.php

This PR adds the SSL status test for the CDN FSD status section
To test setup with a pro license with total CDN and enable/configure FSD. This should set the hostname on save. Then you will need your DNS pointed at the CDN
Then go to the CDN settings page and click on the Check Status button within the FSD box. It should pass. To see the failure state modify Cdnfsd_TotalCdn_Status_Ssl.php to manually trigger a failure
If you remove the ssl from the pull zone manually and then perform the check, it should re-add it and pass the test

Added FSD SSL test
