BoldGrid/w3-total-cache

Generic_Plugin_Admin.php, Root_AdminMenu.php
FAQ Link in Dashboard should open in new tab
=> make FAQ link open in a new window with external url

PgCache_ContentGrabber.php, Util_Request.php, lib/Db/mssql.php, lib/Minify/HTTP/ConditionalGet.php
fixes https://github.com/W3EDGE/w3-total-cache/issues/92
=> Remove deprecated get_magic_quotes_gpc()

BrowserCache_Environment.php, BrowserCache_Environment_Nginx.php, BrowserCache_Page_View_SectionSecurity.php, BrowserCache_Plugin_Admin.php, ConfigKeys.php, Util_Ui.php, inc/options/browsercache.php
Implement "Feature Policy" security header
=> Feature policy header, closes #13

readme.txt
Added Lazy Loading and Purge Stack Trace to description
=> Readme updates for v13

Generic_Plugin_Admin.php, UsageStatistics_Page.php, UsageStatistics_Source_DbQueriesLog.php, UsageStatistics_Source_ObjectCacheLog.php, UsageStatistics_Source_PageCacheLog.php, Util_Widget.php
Changed list methods to avoid syntax errors in PHP <7.
=> Fix list methods

SystemOpCache_GeneralPage_View.php, inc/options/general.php, languages/w3-total-cache.pot, w3-total-cache-api.php
=> i18n Improvment

UserExperience_LazyLoad_Mutator.php
https://github.com/W3EDGE/w3-total-cache/issues/217
=> Fix typo in variable.  Fixes #217

Cache_Memcache.php, Cache_Memcached.php
=> Implemented anatomic incrementing of key version in Memcache(d)

Root_AdminActivation.php, Util_Activation.php
environment exceptions are shown as a admin note. regression in v0.15
=> ignore env exceptions on activation since its handled later

qa/plugins/minify-auto-semicolon/minify-auto-js.php, qa/plugins/minify-auto-semicolon/minify-auto-js1.js, qa/plugins/minify-auto-semicolon/minify-auto-js2.js, qa/plugins/minify-auto-semicolon/minify-auto-js3.js, qa/tests/minify/auto-semicolon.js
Semicolon is added properly due to tests. add coverage to QA
=> Minify semicolon, fixes #48

Generic_Plugin_Admin.php, SetupGuide_Plugin_Admin.php, pub/css/wizard.css, pub/js/setup-guide.js
Replicate the issue:
1. Install the plugin on a fresh install
2. Go to a plugin page -- you get redirected to the Setup Guide
3. Click Accept for the terms
4. Click Skip
5. Go to wp-admin/admin.php?page=w3tc_general#miscellaneous
6. Uncheck `Anonymously track usage to improve product quality` and save the settings
7. Go to wp-admin/admin.php?page=w3tc_setup_guide
8. Click Next and then Test Page Cache
9. See the error in the web console
=> Check for w3tc_ga before use

FeatureShowcase_Plugin_Admin.php, Util_Ui.php, inc/options/general.php, pub/css/options.css
- Added "Learn more" links to some Minify options on `wp-admin/admin.php?page=w3tc_general#minify`.
- Added dashicons next to external links on `wp-admin/admin.php?page=w3tc_feature_showcase`.
=> Minify info links

CdnEngine_S3.php
The regions were updated from the list at https://docs.aws.amazon.com/general/latest/gr/rande.html
=> Update AWS S3 region list.  Fixes #63.  Fixes #189.

PgCache_Environment.php
=> Fixes missing whitespaces in memcached nginx config

lib/Minify/JSMin.php
Added backtick support so that the script recognizes them as a quoting method
=> Fixed JS minify issue with template literal backticks #392

Cdn_Plugin.php
clarify in error log why some functionality doesnt behave as expected when server environment is broken
=> clarify in error log why some functionality doesnt behave as expected, closes #395

Cdn_GeneralPage_View.php, Extension_FragmentCache_GeneralPage_View.php, Generic_WidgetSpreadTheWord_View.php, UsageStatistics_GeneralPage_View.php, UsageStatistics_Page_View_Ad.php, UserExperience_LazyLoad_Page_View.php, inc/options/about.php, inc/options/browsercache.php, inc/options/dashboard.php, inc/options/general.php, inc/options/minify.php, inc/options/minify/css.php, inc/options/objectcache.php
Added missing text domains, translations, and corrected acronyms
=> Added missing text domains, translations and corrected acronyms

pub/js/options.js
=> fix(cdn_test): send correct passive checkbox value

BrowserCache_Page_View_SectionSecurity.php
It appears that most of the existing feature policies were already added. I updated 1 entry whose key didn't match and added 8 missing options
=> Support Feature Policy Security Header #13

ConfigKeys.php, Generic_Environment.php, Generic_Plugin.php, Util_WpFile.php, inc/options/general.php
#420 
#419 
#147 
New toggle setting is located under Performance->General Settings->Miscellaneous 
The robots rule will now be added to the virtual robots.txt via a filter or to the physical robots.txt if it's present. Also if the robots.txt file becomes empty as a result of removing the rule it will delete the file
=> Added robots blocking toggle #147/#419/#420

BrowserCache_Environment.php, BrowserCache_Environment_Nginx.php
bind code to existing config keys
=> extra mime groups other than controlled by settings were added to rules

PgCache_Flush.php, Util_Environment.php, Util_PageUrls.php
=> CPT archive cache doesn't clear on custom post publish/update #139

Extension_CloudFlare_Api.php, Extension_CloudFlare_Widget.php, Extension_CloudFlare_Widget_View.php
=> Fixed cloudflare widget and updated to graphql #387

PgCache_ContentGrabber.php
=> Fix for native WP sitemap caching #241

Util_File.php
It was only checking if the provided path was a directory or not
=> Util_File.php fix for mkdir calls not pre-checking if the provided path is a file

UsageStatistics_GeneralPage_View.php, UsageStatistics_Plugin_Admin.php
Reference: https://wordpress.org/support/topic/access-logs-minimum-permissions/
=> Fix access log test

Cache_Redis.php, Licensing_Plugin_Admin.php, inc/lightbox/self_test.php, inc/options/dashboard.php, inc/options/parts/redis.php, readme.txt, w3-total-cache-api.php, w3-total-cache.php
w3tc test results (4 / 39956 failed)
=> Release 2.2.3

Licensing_Plugin_Admin.php
Error Fixed:
* Missed second parameter when use wp_kses.
=> Fix error: add missed second parameter to wp_kses()

vendor/aws/aws-php-sns-message-validator/.github/ISSUE_TEMPLATE/bug-report.yml, vendor/aws/aws-php-sns-message-validator/.github/ISSUE_TEMPLATE/config.yml, vendor/aws/aws-php-sns-message-validator/.github/ISSUE_TEMPLATE/documentation.yml, vendor/aws/aws-php-sns-message-validator/.github/ISSUE_TEMPLATE/feature-request.yml, vendor/aws/aws-php-sns-message-validator/.github/PULL_REQUEST_TEMPLATE.md, vendor/aws/aws-php-sns-message-validator/.github/workflows/stale_issues.yml, vendor/aws/aws-php-sns-message-validator/.gitignore, vendor/aws/aws-php-sns-message-validator/.travis.yml, vendor/aws/aws-php-sns-message-validator/CODE_OF_CONDUCT.md, vendor/aws/aws-php-sns-message-validator/CONTRIBUTING.md, vendor/aws/aws-php-sns-message-validator/LICENSE.md, vendor/aws/aws-php-sns-message-validator/NOTICE.md, vendor/aws/aws-php-sns-message-validator/README.md, vendor/aws/aws-php-sns-message-validator/composer.json, vendor/aws/aws-php-sns-message-validator/phpunit.xml.dist, vendor/aws/aws-php-sns-message-validator/src/Exception/InvalidSnsMessageException.php, vendor/aws/aws-php-sns-message-validator/src/Message.php, vendor/aws/aws-php-sns-message-validator/src/MessageValidator.php, vendor/aws/aws-php-sns-message-validator/tests/FunctionalValidationsTest.php, vendor/aws/aws-php-sns-message-validator/tests/MessageTest.php, vendor/aws/aws-php-sns-message-validator/tests/MessageValidatorTest.php, vendor/aws/aws-php-sns-message-validator/tests/MockPhpStream.php
To resolve https://wordpress.org/support/topic/fatal-error-4216/
=> Add sns-message-validator

readme.txt, w3-total-cache-api.php, w3-total-cache.php
https://github.com/W3EDGE/w3-total-cache/compare/2.2.3...master
=> Release 2.2.4

Base_Page_Settings.php, Cdn_Plugin.php, Cdn_Util.php, Cdnfsd_CacheFlush.php, ConfigKeys.php, Generic_Plugin_Admin.php, inc/options/cdn.php
Addition to resolution for https://github.com/W3EDGE/w3-total-cache/issues/535 to help prevent unnecessary Cloudfront Invalidation charges
=> Change default for cdn.flush_manually to true

Cdn_Core.php
Reference: 
https://wordpress.org/support/topic/push-cdn-and-custom-urls/
=> Added filter hook w3tc_uri_cdn_uri to uri_to_cdn_uri function

qa/plugins/pagecache/skip-flush-of-aloof-plugins-action.php, qa/plugins/pagecache/skip-flush-of-aloof-plugins.php, qa/tests/pagecache/skip-flush-of-aloof-plugins.js
sample code for skipping pagecache flush when called too frequently by aloof plugins
=> sample code for skipping pagecache flush when called too frequently

DbCache_Plugin.php, ObjectCache_Plugin.php, Util_AttachToActions.php, Varnish_Plugin.php, readme.txt, w3-total-cache-api.php, w3-total-cache.php
To test:
1. Approve a comment while having the page cache enabled.  Also, test with object and database cache enabled.
2. Create or modify a post while having Varnish configured.  The issue occurs when a post is created or modified, and the user has the reverse proxy Varnish setting enabled with Varnish installed and configured.
=> Release 2.2.12

FeatureShowcase_Plugin_Admin.php, Generic_AdminNotes.php, Licensing_Core.php, PageSpeed_Api.php, PageSpeed_Data.php, PageSpeed_Instructions.php, PageSpeed_Page.php, PageSpeed_Page_View.js, PageSpeed_Page_View.php, PageSpeed_Page_View_FromAPI.php, PageSpeed_Widget.php, PageSpeed_Widget_View.js, PageSpeed_Widget_View.php, PageSpeed_Widget_View_FromApi.php, PgCache_ContentGrabber.php, README.md, Util_File.php, Util_Ui.php, composer.json, inc/options/general.php, inc/options/pgcache.php, languages/w3-total-cache.pot, lib/Minify/Minify/HTML.php, qa/env/scripts/restore-final.rb, readme.txt, w3-total-cache-api.php, w3-total-cache.php
This has run through AWS testing (automated and manual) and smoke tests.
Diff: https://github.com/BoldGrid/w3-total-cache/compare/2.2.12...release-2.3.0
=> Release 2.3.0

Util_PageSpeed.php
This PR simply expands on the comments for the logic applied to the source/url fields to better clarify why the logic check exists.
=> Small tweak to PageSpeed comments

qa/lib/w3tc.js, qa/lib/wp.js, qa/tests/activation/addons-not-writable.js, qa/tests/browsercache/cdn.js, qa/tests/browsercache/replace.js, qa/tests/browsercache/uploads-headers.js, qa/tests/cdn/file-upload.js, qa/tests/cdn/ftp-minify-manual.js, qa/tests/cdn/ftp-test-button.js, qa/tests/cdn/pull-custom.js, qa/tests/generic/box-valid.js, qa/tests/generic/compatibility-check.js, qa/tests/generic/import-export.js, qa/tests/generic/preview-mode.js, qa/tests/generic/referrer-groups-redirect.js, qa/tests/generic/referrer-groups-theme.js, qa/tests/generic/user-agent-groups.js, qa/tests/generic/user-signup-single.js, qa/tests/generic/user-signup-subdomain.js, qa/tests/minify/manual-non-blocking.js, qa/tests/minify/manual-placement.js, qa/tests/minify/manual-url-deformation.js, qa/tests/minify/manual.js, qa/tests/pagecache/flush.js, qa/tests/pagecache/skip-flush-of-aloof-plugins.js, qa/tests/pagecache/user-roles.js
With the changes to the HTML markup in the marketing-v2 branch many of the tests were targeting removed save buttons from individual setting sections. This PR updates the tests to target the save-bar save button
=> Updated QA tests to target moved save button correctly.

Cdn_StackPath2_Page_View.php, Cdn_StackPath2_Widget_View_Unauthorized.php
I found only 2 references to StackPath pricing. If there are more please indicate what file needs to be updated
=> Updated pricing for StackPath to match their site

Extension_FragmentCache_Plugin.php
After some peer review of recent PRs we identified some improvements that could be made. This PR cleans up a small bit of code
=> Small Fragment Cache Tweak

FeatureShowcase_Plugin_Admin.php, UserExperience_DeferScripts_Page_View.php, UserExperience_GeneralPage_View.php, Util_Ui.php
This PR rebrands the feature from Defer Scripts to Delay Scripts
=> Rebrand Defer Scripts

FeatureShowcase_Plugin_Admin.php, FeatureShowcase_Plugin_Admin_View.php, UserExperience_GeneralPage_View.php, inc/options/common/footer.php, pub/css/feature-showcase.css
This PR tweaks some text for the Delay Scripts and adds a link to the footer template
Additionally it modifies the layout and appearance of the Feature Showcase page so new items are located in the top section with larger cards and a modified "new" look
=> Delay scripts UI

Extensions_Util.php, Generic_AdminActions_Default.php, inc/options/general.php
See https://github.com/BoldGrid/w3-total-cache/issues/769
=> WebP Converter activation

.travis.yml, Cdnfsd_Core.php, composer.lock, inc/options/cdn.php, package.json, yarn.lock
Tests pass.  Review https://app.codecov.io/github/BoldGrid/w3-total-cache/tree/travis-codecov and Travis CI builds.  There were a couple of PHP lint items fixed.
=> Add Codecov to Travis CI

Util_PageUrls.php, Util_Ui.php
Fixes page mapping for when a page id is not found.  Also adds page map filtering.
=> Fix page mapping

pub/css/feature-showcase.css
On Feature Showcase, the new card bottom ribbon should now have better contrast
=> Fix Feature Showcase New Card Bottom Ribbon

Cache_File.php, PgCache_Environment.php, composer.lock, languages/w3-total-cache.pot, package.json, qa/env/100-generate-envs, qa/env/scripts/http-server-error-log-read.sh, qa/env/scripts/init-image/150-mocha.sh, qa/lib/sys.js, qa/lib/w3tc.js, qa/lib/wp.js, qa/tests/activation/addons-not-writable.js, qa/tests/activation/upgrade.js, qa/tests/cdn/ftp-test-button.js, qa/tests/dbcache/garbage-collection.js, qa/tests/generic/compatibility-check.js, qa/tests/generic/user-signup-single.js, qa/tests/objectcache/basic.js, qa/tests/objectcache/default-lifetime-objects.js, qa/tests/objectcache/garbage-collection.js, qa/tests/pagecache/user-roles.js, readme.txt, w3-total-cache-api.php, w3-total-cache.php, yarn.lock
This release branch includes the usual version bump updates plus updates for the automated test on the latest version of Puppeteer.
=> Release 2.7.1

UserExperience_Remove_CssJs_Mutator.php, UserExperience_Remove_CssJs_Page_View.php, Util_Environment.php, tests/admin/class-w3tc-admin-util-environment.php
There was an issue matching partial/relative URLs/URIs.  I created a new static method instead of using `array_intersect()`.  I also updated the array of "current_pages".
=> Fix Remove CSS/JS URL matching

.travis.yml, bin/release.sh
See https://app.travis-ci.com/github/BoldGrid/w3-total-cache/jobs/624173973#L860 for proof.
=> Fix WP-CLI run on Travis CI deploy

Util_AttachToActions.php
This PR addresses both an undefined variable warning that can occur as well as an issue with handling the flush of both a parent and it's child
=> On Post Change Parent Issue

PageSpeed_Data.php
This PR simply removes 2 metrics that were removed from PageSpeed on 4/22/24
=> PageSpeed Update

BrowserCache_Environment.php, BrowserCache_Environment_LiteSpeed.php, BrowserCache_Environment_Nginx.php, BrowserCache_Plugin.php, Minify_Environment.php, PgCache_ContentGrabber.php, PgCache_Environment.php, inc/options/browsercache.php
=> Remove no-store header - fixes #648

FeatureShowcase_Plugin_Admin.php
Fixes https://github.com/BoldGrid/w3-total-cache-internal/issues/1817
- The Eliminate Render Blocking CSS
- Extension Framework
- Rest API Caching
- Content Delivery Network
=> Update links on the Feature Showcase page

inc/options/common/top_nav_bar.php
This PR removes the links from the top nav and sidebar when the extension is disabled or when not pro
=> Fragment Cache link issue

DbCache_Plugin.php, inc/options/general.php, pub/css/options.css, pub/js/options.js
This PR just adds an admin notice when the disk engine is selected for DB Cache that suggests using memory based caching instead
=> DB Cache Disk Notice

Util_WpFile.php
=> fixes pr-670

ConfigSettingsTabsKeys.php, Util_Ui.php, pub/css/options.css, pub/js/options.js
Fixes issues posted in the nest projects
=> Update to Premium Services tab

Generic_Plugin_Admin.php
Adds the ability to track all settings tabs that have the data-tab-type attr
=> add ability to track all settings tabs via GA

BrowserCache_Plugin.php, Extension_ImageService_Plugin_Admin.php, Extensions_Plugin_Admin.php, Generic_Plugin_Admin.php, Generic_Plugin_AdminNotices.php, Generic_WidgetStats.php, ObjectCache_WpObjectCache_Regular.php, PgCache_ContentGrabber.php, Util_Debug.php, Util_File.php, inc/options/common/footer.php, inc/options/common/top_nav_bar.php
To test, follow the directions posted in Slack.
Reference links:
https://wordpress.org/documentation/article/roles-and-capabilities/
https://developer.wordpress.org/apis/hooks/action-reference/
=> Add user compatibility checks

Extension_ImageService_Widget.js, Extension_ImageService_Widget.php, Extension_ImageService_Widget_View.php
This PR simply adds a notice to the WebP widget indicating that upgrading to pro increases limits
Additionally this PR fixes both the widget gauge yellow/red ranges and fixes the monthly hourly limit gauge using the free limit
=> WebP Pro Upgrade Notice

composer.json
preferable use the original than discontinued clones https://packagist.org/?query=w3&type=wordpress-plugin
=> Add package details @ composer.json

Cli.php
From the command line use "wp help" which will list the aliases and show the added descriptions
=> Added descriptions for registered CLI aliases.

Licensing_Core.php, Licensing_Plugin_Admin.php, Root_AdminActivation.php, Root_Environment.php, inc/options/general.php, pub/js/options.js
This PR simply removes the `verify license key` button on the General Settings page and adds an admin notice that displays on save indicating the result of license activation
=> License Verify/Apply Update

Generic_Plugin_Survey.php, inc/lightbox/exit_survey.php, pub/css/exit-survey.css, pub/js/exit-survey.js
This PR fixes a bug that prevented the email input from submitting to the API. It also adjust the other input field to show for any deactivation reason selected. This was adjusted in hopes of collecting more info on the selected reason for deactivation
=> Survey Fixes/Adjustments

SetupGuide_Plugin_Admin.php, composer.lock, languages/w3-total-cache.pot, pub/js/setup-guide.js, readme.txt, w3-total-cache-api.php, w3-total-cache.php, yarn.lock
* Fix: Exit survey email field submission
* Fix: Setup Guide analytics
* Update: Allow deleting plugin data when skipping the exit survey on deactivation
* Update: aws/aws-php-sns-message-validator (1.9.0 => 1.9.1)
=> Release 2.8.7

Extension_AiCrawler_Page.php, Extension_AiCrawler_Page_View.php, Extension_AiCrawler_Plugin.php, Extension_AiCrawler_Plugin_Admin.php, Extensions_Plugin_Admin.php
Story ticket: [ENG5-191](https://imh-internal.atlassian.net/browse/ENG5-191)
Code Review ticket: [ENG5-226](https://imh-internal.atlassian.net/browse/ENG5-226)
* Add AI Crawler extension core files
[ENG5-191]: https://imh-internal.atlassian.net/browse/ENG5-191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG5-226]: https://imh-internal.atlassian.net/browse/ENG5-226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ENG5-191 Add basic AI Crawler extension core files(#1141)

Extension_AiCrawler_Central_Api.php, Extension_AiCrawler_Page.js, Extension_AiCrawler_Page.php, Extension_AiCrawler_Page_View.php, Extension_AiCrawler_Page_View_Settings.php, Extension_AiCrawler_Page_View_Tools.php, Extension_AiCrawler_Plugin.php, Extension_AiCrawler_Plugin_Admin.php, Extension_AiCrawler_Util.php, Extensions_Plugin_Admin.php, Generic_AdminActions_Default.php, Util_Ui.php
This PR adds Configuration and Tools sections to the AI Crawler settings page. To test, simply apply new values for each setting in the Configuration section and save the settings. These should apply and be shown on page reload
The "Test" button for the IMH Central token, and the tools functionality isn't included in this PR and should be ignored
=> AI Crawler Settings Page

Cache_File_Generic.php
Canonicalize path to avoid unexpected variants
=> Fix cache read path

Extension_AiCrawler_Plugin_Admin.php, Extension_AiCrawler_SiteHealth.php, Extension_AiCrawler_Util.php
This PR simply adds a status test and debug info section on under the Site Health WordPress tool page
/wp-admin/site-health.php?tab&aicrawler_dummy=mixed
/wp-admin/site-health.php?tab=debug&aicrawler_dummy=mixed
=> Site Health Addition

Extension_AiCrawler_Mock_Api.php, Extension_AiCrawler_Plugin.php
Story Ticket: [ENG5-284](https://imh-internal.atlassian.net/browse/ENG5-284)
Code Review Ticket: [ENG5-287](https://imh-internal.atlassian.net/browse/ENG5-287)
Acceptence Testing Ticket: [ENG5-286](https://imh-internal.atlassian.net/browse/ENG5-286)
[ENG5-284]: https://imh-internal.atlassian.net/browse/ENG5-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG5-287]: https://imh-internal.atlassian.net/browse/ENG5-287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG5-286]: https://imh-internal.atlassian.net/browse/ENG5-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ENG5-284 create mock data class

Extension_AiCrawler_Plugin.php, Extension_AiCrawler_Util.php, Extensions_Plugin_Admin.php, FeatureShowcase_Plugin_Admin.php
Jira Story Ticket: [ENG5-208](https://imh-internal.atlassian.net/browse/ENG5-208)
Code Review Ticket: [ENG5-349](https://imh-internal.atlassian.net/browse/ENG5-349)
Acceptance Testing: [ENG5-350](https://imh-internal.atlassian.net/browse/ENG5-350)
[ENG5-208]: https://imh-internal.atlassian.net/browse/ENG5-208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG5-349]: https://imh-internal.atlassian.net/browse/ENG5-349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG5-350]: https://imh-internal.atlassian.net/browse/ENG5-350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ENG5-208 add central_connect option check

Extension_AiCrawler_Markdown.php, Extension_AiCrawler_Plugin.php, Extension_AiCrawler_Plugin_Admin.php
Story Ticket: [ENG5-210](https://imh-internal.atlassian.net/browse/ENG5-210)
Code Review Ticket: [ENG5-345](https://imh-internal.atlassian.net/browse/ENG5-345)
Acceptance Testing: [ENG5-346](https://imh-internal.atlassian.net/browse/ENG5-346)
[ENG5-210]: https://imh-internal.atlassian.net/browse/ENG5-210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG5-345]: https://imh-internal.atlassian.net/browse/ENG5-345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG5-346]: https://imh-internal.atlassian.net/browse/ENG5-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ENG5-210 auto generate on save

Extension_AiCrawler_Page.js, Extension_AiCrawler_Page_View_Tools.php, Extension_AiCrawler_Plugin_Admin.php
Jira Story Ticket: [ENG5-196](https://imh-internal.atlassian.net/browse/ENG5-196)
Code Review Ticket: [ENG5-355](https://imh-internal.atlassian.net/browse/ENG5-355)
Acceptance Testing Ticket: [ENG5-356](https://imh-internal.atlassian.net/browse/ENG5-356)
[ENG5-196]: https://imh-internal.atlassian.net/browse/ENG5-196?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG5-355]: https://imh-internal.atlassian.net/browse/ENG5-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG5-356]: https://imh-internal.atlassian.net/browse/ENG5-356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ENG5-196 add regenerate all support (#1179)

Extension_AiCrawler_LlmsTxt_Server.php, Extension_AiCrawler_Markdown.php, Extension_AiCrawler_Markdown_Server.php, Extension_AiCrawler_Plugin.php, Extension_AiCrawler_Plugin_Admin.php
Story Ticket: [ENG5-198](https://imh-internal.atlassian.net/browse/ENG5-198)
Code Review Ticket: [ENG5-352](https://imh-internal.atlassian.net/browse/ENG5-352)
Acceptance Testing Ticket: [ENG5-353](https://imh-internal.atlassian.net/browse/ENG5-353)
[ENG5-198]: https://imh-internal.atlassian.net/browse/ENG5-198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG5-352]: https://imh-internal.atlassian.net/browse/ENG5-352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ENG5-353]: https://imh-internal.atlassian.net/browse/ENG5-353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=>  ENG5-198 serve markdown

inc/options/cdn.php
Added Text Domain to two strings in cdn.php
=> Added Text Domain to two strings in cdn.php

inc/options/general.php
Added Text Domain to two strings in general.php
=> Added Text Domain to two strings in general.php

inc/options/browsercache.php
Added Text Domain to one string in browsercache.php
=> Added Text Domain to one string in browsercache.php

Generic_Plugin_AdminCompatibility.php
Added Text Domain to one string in Generic_Plugin_AdminCompatibility.php
=> Added Text Domain to one string in Generic_Plugin_AdminCompatibility.php

Cdn_TotalCdn_Api.php, tests/admin/class-w3tc-cdn-totalcdn-api-test.php
This implements a new API method and PHPUnit tests for it.
To test:
1. Run PHPUnit tests.  Can target the new tests using `--filter=W3tc_Cdn_TotalCdn_Api_Test`.
=> Add custom hostname check

AGENTS.md, CdnEngine_Mirror_TotalCdn.php, Cdn_Page.php, Cdn_TotalCdn_Api.php, Cdn_TotalCdn_CustomHostname.php, Cdn_TotalCdn_Page.php, Cdn_TotalCdn_Page_View.php, Cdn_TotalCdn_Page_View_Purge_Urls.php, Cdn_TotalCdn_Popup.php, Cdn_TotalCdn_Popup_View_Deauthorize.php, Cdn_TotalCdn_Widget.php, Cdn_TotalCdn_Widget_View_Unauthorized.php, Generic_Plugin_Admin.php, tests/admin/class-w3tc-cdn-totalcdn-api-test.php, tests/admin/class-w3tc-cdn-totalcdn-customhostname-test.php
https://imh-internal.atlassian.net/browse/ENG5-469
To test:
1. Add a license key having Pro and tcdn.
1. Ensure that CDN was configured (purchase process or auto-configure).
1. Go to the General Settings page.
1. Disable CDN.
1. Enable FSD.
1. Look for any error messages -- none should be raised.
1. Check your Bunny Dashboard to see if your site's hostname has been added to your pull zone.
1. Change the code to force a failure to see error messages.
=> On FSD enable, check/add hostname
